# toy_en_de.yaml

## Where the samples will be written
save_data: run/test
## Where the vocab(s) will be written
src_vocab: run/test.vocab.src
tgt_vocab: run/test.vocab.tgt
# Prevent overwriting existing files in the folder
overwrite: False

# Corpus opts:
data:
    corpus_1:
        path_src: data/src/src-train.txt
        path_tgt: data/trg/trg-train.txt
    valid:
        path_src: data/src/src-val.txt
        path_tgt: data/trg/trg-val.txt

# General opts
save_model: foo
save_checkpoint_steps: 1000
valid_steps: 1000
train_steps: 20000

# Batching
bucket_size: 32768
world_size: 1
gpu_ranks: [0]
num_workers: 4
batch_type: "tokens"
batch_size: 4096
valid_batch_size: 8
max_generator_batches: 2
accum_count: [4]
accum_steps: [0]

# Optimization
model_dtype: "fp32"
optim: "adam"
learning_rate: 2
warmup_steps: 8000
decay_method: "noam"
adam_beta2: 0.998
max_grad_norm: 0
label_smoothing: 0.1
param_init: 0
param_init_glorot: true
normalization: "tokens"

# Model
encoder_type: transformer
decoder_type: transformer
position_encoding: true
enc_layers: 6
dec_layers: 6
heads: 8
hidden_size: 512
word_vec_size: 512
transformer_ff: 2048
dropout_steps: [0]
dropout: [0.1]
attention_dropout: [0.1]